# Generated by Django 2.2.1 on 2019-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writting',
            name='tags',
            field=models.ManyToManyField(related_name='writtings', to='writtings.Tag'),
        ),
    ]
